<a href="https://colab.research.google.com/github/vedkanojia2304-svg/python_ML-practice/blob/main/NumPy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Activity 1 : create a array
import numpy as np
arr = np.array([10,28,39,50,9])
print(arr)

b = np.linspace(0,1,5)
print(b)

[10 28 39 50  9]
[0.   0.25 0.5  0.75 1.  ]


In [9]:
# Activity 2 : perform basic matrix operation
import numpy as np
a = np.array([[1,2] , [2,3]])
b = np.array([[2,3] , [6,7]])
print("matrix a: ")
print(a)

print("matrix b: ")
print(b)

print("\naddition: ")
print(a+b)

print("\nsubtraction: ")
print(a-b)

print("\nelement wise multiplication: ")
print(a*b)

print("\nmatrix wise multiplication: ")
print(a@b)



matrix a: 
[[1 2]
 [2 3]]
matrix b: 
[[2 3]
 [6 7]]

addition: 
[[ 3  5]
 [ 8 10]]

subtraction: 
[[-1 -1]
 [-4 -4]]

element wise multiplication: 
[[ 2  6]
 [12 21]]

matrix wise multiplication: 
[[14 17]
 [22 27]]


In [10]:
# acitivity 3: statistics

marks = np.array([70,45,5,6,7,78])

print(np.min(marks))
print(np.max(marks))
print(np.mean(marks))
print(np.median(marks))
print(np.std(marks))

5
78
35.166666666666664
26.0
30.81891554801297


In [11]:
"""weather data of july days in udupi
find hottest and coldest day
avg temp
dates above 35 deg cel"""

# July temperatures (Max, Min)
temp = [
    (26,23), (28,24), (28,24), (29,24), (30,25),
    (30,24), (30,23), (30,24), (31,26), (30,25),
    (30,24), (30,24), (30,26), (31,25), (31,25),
    (30,24), (27,22), (29,23), (29,25), (27,24),
    (29,24), (26,24), (29,23), (30,24), (29,23),
    (29,24), (30,24), (28,24), (29,25), (30,24),
    (30,25)
]

# Average temperature for each day
avg = []
for t in temp:
    avg.append((t[0] + t[1]) / 2)

print("Daily Average Temperatures:")
print(avg)

# Monthly average
monthly_avg = sum(avg) / len(avg)
print("Monthly Average:", round(monthly_avg, 2), "°C")

# Hottest day
max_temp = max(t[0] for t in temp)
print("Highest Temperature:", max_temp, "°C")

print("Hottest Day(s):")
for i in range(len(temp)):
    if temp[i][0] == max_temp:
        print("July", i + 1)

# Coldest day
min_temp = min(t[0] for t in temp)
print("Lowest Temperature:", min_temp, "°C")

print("Coldest Day(s):")
for i in range(len(temp)):
    if temp[i][0] == min_temp:
        print("July", i + 1)

# Days above 35°C
print("Days Above 35°C:")
found = False
for i in range(len(temp)):
    if temp[i][0] > 35:
        print("July", i + 1)
        found = True

if not found:
    print("None")



Daily Average Temperatures:
[24.5, 26.0, 26.0, 26.5, 27.5, 27.0, 26.5, 27.0, 28.5, 27.5, 27.0, 27.0, 28.0, 28.0, 28.0, 27.0, 24.5, 26.0, 27.0, 25.5, 26.5, 25.0, 26.0, 27.0, 26.0, 26.5, 27.0, 26.0, 27.0, 27.0, 27.5]
Monthly Average: 26.66 °C
Highest Temperature: 31 °C
Hottest Day(s):
July 9
July 14
July 15
Lowest Temperature: 26 °C
Coldest Day(s):
July 1
July 22
Days Above 35°C:
None
